### ISSUE TITLE
g++ 7.2 fails to compile

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18#377]
I'm seeing the following error when building with g++ 7.2

f18/lib/evaluate/formatting.cc:220:51: error: no matching function for call to ?GetPrecedence(const Fortran::evaluate::NullPointer&)?
           [](const auto &x) { return GetPrecedence(x); },
                                      ~~~~~~~~~~~~~^~~

(Same code compiles with g++ 8.2, however.)
